# Generated by Django 4.1.7 on 2023-03-29 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTruck',
            fields=[
                ('boo_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_cit', models.CharField(max_length=100)),
                ('p_addres1', models.CharField(max_length=100)),
                ('p_addres2', models.CharField(max_length=100)),
                ('p_distric', models.CharField(max_length=100)),
                ('p_stat', models.CharField(max_length=100)),
                ('p_pincod', models.CharField(max_length=100)),
                ('d_cit', models.CharField(max_length=100)),
                ('d_addres1', models.CharField(max_length=100)),
                ('d_addres2', models.CharField(max_length=100)),
                ('d_distric', models.CharField(max_length=100)),
                ('d_stat', models.CharField(max_length=100)),
                ('d_pincod', models.CharField(max_length=100)),
                ('good_typ', models.CharField(choices=[('Household', 'Household'), ('Beverages', 'Beverages'), ('Paints', 'Paints'), ('Steel', 'Steel'), ('Electronics', 'Electronic'), ('others', 'others'), ('None', 'None')], default='None', max_length=50)),
                ('bookingdat', models.DateTimeField()),
                ('weigh', models.CharField(max_length=100)),
                ('service', models.CharField(choices=[('Loading', 'Loading'), ('Unloading', 'Unloading'), ('Cardboard Packing', 'Cardboard Packing'), ('Storage', 'Storage')], default='None', max_length=50)),
                ('load_descriptio', models.CharField(max_length=100)),
                ('statu', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('None', 'None')], default='None', max_length=100)),
                ('us_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
