# Generated by Django 4.1.7 on 2023-03-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_commonman',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_driver',
        ),
        migrations.AddField(
            model_name='account',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('is_admin', 'is_admin'), ('is_consignor', 'is_consignor')], max_length=100),
        ),
    ]
