# Generated by Django 4.1.7 on 2023-03-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_account_is_commonman_remove_account_is_driver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='account',
            name='state',
        ),
        migrations.RemoveField(
            model_name='account',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='account',
            name='is_commonman',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_driver',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('is_admin', 'is_admin'), ('is_consignor', 'is_consignor'), ('is_commonman', 'is_commonman'), ('is_driver', 'is_driver')], max_length=100),
        ),
    ]
