# Generated by Django 4.1.7 on 2023-03-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_btruck_veh_id_alter_btruck_statu'),
    ]

    operations = [
        migrations.AddField(
            model_name='btruck',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
