# Generated by Django 4.1.7 on 2023-05-09 06:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_fueldetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='fueldetail',
            name='fuel_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
