# Generated by Django 4.1.7 on 2023-02-27 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_is_active_account_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='business',
        ),
        migrations.RemoveField(
            model_name='account',
            name='cname',
        ),
        migrations.RemoveField(
            model_name='account',
            name='ctype',
        ),
    ]
