# Generated by Django 4.1.7 on 2023-03-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_btruck_is_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='btruck',
            name='is_booked',
        ),
        migrations.AddField(
            model_name='account',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
