# Generated by Django 4.1.7 on 2023-05-09 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_fueldetail_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fueldetail',
            name='added_driver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truck_driver', to=settings.AUTH_USER_MODEL),
        ),
    ]
