# Generated by Django 4.1.7 on 2023-03-23 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_groups_account_is_superuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLogin',
            fields=[
                ('driver_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
