# Generated by Django 4.1.7 on 2023-03-30 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_companytruck'),
        ('accounts', '0005_remove_btruck_is_booked_account_is_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='btruck',
            name='dr_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='btruck',
            name='us_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consignor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='btruck',
            name='veh_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.companytruck'),
        ),
    ]
