# Generated by Django 4.1.7 on 2023-03-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_driverlogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.BigIntegerField(default=0, unique=True),
        ),
    ]
