# Generated by Django 4.1.7 on 2023-04-05 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_companytruck'),
        ('accounts', '0006_btruck_dr_id_alter_btruck_us_id_alter_btruck_veh_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btruck',
            name='dr_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='btruck',
            name='veh_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.companytruck'),
        ),
    ]
