# Generated by Django 4.1.7 on 2023-04-20 06:00

from django.db import migrations
import django.utils.timezone
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_btruck_dr_id_alter_btruck_veh_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='btruck',
            name='location',
            field=location_field.models.plain.PlainLocationField(default=django.utils.timezone.now, max_length=63),
            preserve_default=False,
        ),
    ]
