# Generated by Django 4.1.7 on 2023-03-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('v_id', models.AutoField(primary_key=True, serialize=False)),
                ('register_num', models.CharField(max_length=100, unique=True)),
                ('reg_owner', models.CharField(max_length=100)),
                ('regd_address', models.CharField(max_length=100)),
                ('maker_class', models.CharField(max_length=100)),
                ('vehicles_class', models.CharField(max_length=100)),
                ('fuel', models.CharField(max_length=100)),
                ('engine', models.CharField(max_length=100)),
                ('insurance', models.CharField(max_length=100)),
                ('is_booked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('register_no', models.CharField(max_length=100, unique=True)),
                ('regd_owner', models.CharField(max_length=100)),
                ('reg_address', models.CharField(max_length=100)),
                ('makers_class', models.CharField(max_length=100)),
                ('vehicle_class', models.CharField(max_length=100)),
                ('fuel', models.CharField(max_length=100)),
                ('engine', models.CharField(max_length=100)),
                ('insurance', models.CharField(max_length=100)),
            ],
        ),
    ]
