# Generated by Django 4.1.7 on 2023-02-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('register_no', models.CharField(max_length=100)),
                ('regd_owner', models.CharField(max_length=100)),
                ('reg_address', models.CharField(max_length=100)),
                ('makers_class', models.CharField(max_length=100)),
                ('vehicle_class', models.CharField(max_length=100)),
                ('fuel', models.CharField(max_length=100)),
                ('engine', models.CharField(max_length=100)),
                ('insurance', models.CharField(max_length=100)),
            ],
        ),
    ]
