# Generated by Django 4.1.7 on 2023-02-27 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_address', models.CharField(max_length=200)),
                ('driver_email', models.CharField(max_length=100, unique=True)),
                ('driver_phone', models.BigIntegerField()),
                ('driver_licence', models.CharField(max_length=100)),
                ('driver_image', models.ImageField(upload_to='')),
                ('driver_vehicle', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='Home.vehicle', verbose_name='register_no')),
            ],
        ),
    ]
