# Generated by Django 4.1.7 on 2023-03-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyTruck',
            fields=[
                ('truck_id', models.AutoField(primary_key=True, serialize=False)),
                ('registeration_no', models.CharField(max_length=100, unique=True)),
                ('registered_owner', models.CharField(max_length=100)),
                ('registered_address', models.CharField(max_length=200)),
                ('makerss_class', models.CharField(max_length=100)),
                ('truck_class', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(max_length=100)),
                ('engine_name', models.CharField(max_length=100)),
                ('insurance_year', models.CharField(max_length=100)),
                ('is_booked', models.BooleanField(default=False)),
            ],
        ),
    ]
