# Generated by Django 4.1.7 on 2023-03-22 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelManagement',
            fields=[
                ('fuel_id', models.AutoField(primary_key=True, serialize=False)),
                ('fuel_quantity', models.CharField(max_length=200)),
                ('odometer_reading', models.CharField(max_length=200)),
                ('fill_date', models.DateField()),
                ('amount', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=200)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.driver')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.vehicle')),
            ],
        ),
    ]
