# Generated by Django 4.1.7 on 2023-03-23 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_fuelmanagement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FuelManagement',
            new_name='AddFuel',
        ),
    ]
