# Generated by Django 4.1.7 on 2023-03-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_delete_addfuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_phone',
            field=models.BigIntegerField(unique=True),
        ),
    ]
