# Generated by Django 4.1.7 on 2023-03-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_alter_driver_driver_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='driver_image',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='driver_vehicle',
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_email',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_licence',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_phone',
            field=models.BigIntegerField(default=0, unique=True),
        ),
    ]
